name: Build KIE Tools

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'The GitHub repository to build (e.g., kiegroup/kie-tools)'
        required: true
      branch:
        description: 'The branch to build (e.g., main)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout specified repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.branch }}
          
      - name: "Setup environment"
        uses: ./.github/actions/setup-env
        with:
          working_dir: kie-tools

      - name: Build KIE Tools
        run: mvn clean install

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kie-tools-artifacts
          path: |
            packages/sonataflow-quarkus-devui/sonataflow-quarkus-devui/target/sonataflow-quarkus-devui-999-SNAPSHOT.jar
            packages/sonataflow-quarkus-devui/sonataflow-quarkus-devui-deployment/target/sonataflow-quarkus-devui-deployment-999-SNAPSHOT.jar
            packages/sonataflow-management-console-webapp/target/sonataflow-management-console-webapp-999-SNAPSHOT-image-build.zip
