name: Build KIE Tools

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'The GitHub repository to build (e.g., kiegroup/kie-tools)'
        required: true
      branch:
        description: 'The branch to build (e.g., main)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout specified repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.branch }}

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Set up Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm@9.3.0

      - name: Install Go
        run: |
          wget https://golang.org/dl/go1.21.9.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.21.9.linux-amd64.tar.gz
          echo "export PATH=$PATH:/usr/local/go/bin" >> $GITHUB_ENV

      - name: Set up Python 3.12
        run: sudo apt-get install python3.12

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Install Make and xmllint
        run: |
          sudo apt-get update
          sudo apt-get install -y make libxml2-utils

      - name: Build KIE Tools
        run: mvn clean install

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kie-tools-artifacts
          path: |
            packages/sonataflow-quarkus-devui/sonataflow-quarkus-devui/target/sonataflow-quarkus-devui-999-SNAPSHOT.jar
            packages/sonataflow-quarkus-devui/sonataflow-quarkus-devui-deployment/target/sonataflow-quarkus-devui-deployment-999-SNAPSHOT.jar
            packages/sonataflow-management-console-webapp/target/sonataflow-management-console-webapp-999-SNAPSHOT-image-build.zip
